// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './server'

export type PageName = 'Home' | 'Me' | 'Notes/Edit' | 'Notes/Index' | 'Notes/New' | 'Notes/Show' | 'Scenarios/Index'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Home': unknown
    'Me': unknown
    'Notes/Edit': unknown
    'Notes/Index': unknown
    'Notes/New': unknown
    'Notes/Show': unknown
    'Scenarios/Index': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
